name: whampy

channels:
    - conda-forge

dependencies:
    - python=>3.6
    - sphinx-astropy
    - astropy
    - numpy
    - matplotlib
    - seaborn
    # - pip
    - pip:
        - sdss-marvin
        - extinction
    #     - git+https://github.com/matplotlib/basemap.git
#       - dependency_from_pip
